bases:
  - ../../bases/open-policy-agent
  - ../../bases/cert-manager
  - ../../bases/rbac

configMapGenerator:
- name: istio
  namespace: opa
  files:
  - policies/istio.rego

generatorOptions:
  disableNameSuffixHash: true
  labels:
    openpolicyagent.org/policy: rego

patches:
- patch: |-
    - op: replace
      path: /spec/values/imageTag
      value: 0.19.1
  target:
    kind: HelmRelease
    name: opa
